openapi: 3.0.0
info:
  title: Babylon PTE API
  description: Babylon Public Test Environment (PTE) API specification.
  version: 1.0.0-draft
servers:
  - url: http://127.0.0.1:3331/
paths:
  /show/{address}:
    get:
      summary: Shows an entity on ledger.
      parameters:
        - name: address
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: #
                $ref: '#/components/schemas/ShowResponse'
        '500':
          description: Runtime failure
components:
  schemas:
    ShowResponse:
      type: object
      properties:
        package:
          type: string
        code_size:
          type: integer
          format: int64