openapi: 3.0.0
info:
  title: Babylon PTE API
  description: Babylon Public Test Environment (PTE) API specification.
  version: 1.0.0-draft
servers:
  - url: http://127.0.0.1:3331/
paths:
  /component/{address}:
    get:
      summary: Get info about a component
      operationId: getComponent
      parameters:
        - name: address
          description: The component address
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Component"
        "404":
          description: Component not found
        "500":
          description: Runtime failure
  /resource/{address}:
    get:
      summary: Get info about a resource
      operationId: getResource
      parameters:
        - name: address
          description: The resource address
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Resource"
        "404":
          description: Resource not found
        "500":
          description: Runtime failure
  /nonce:
    get:
      summary: Get the nonce of a signer set
      operationId: getNonce
      parameters:
        - in: query
          name: signers
          description: The signer public keys
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: integer
        "500":
          description: Runtime failure
  /receipt/{hash}:
    get:
      summary: Retrieve a transaction receipt (NOT IMPLEMENTED).
      operationId: getReceipt
      parameters:
        - name: hash
          description: The transaction hash
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Receipt"
        "404":
          description: Transaction not found
  /transaction/{hash}:
    get:
      summary: Retrieve a transaction (NOT IMPLEMENTED).
      operationId: getTransaction
      parameters:
        - name: hash
          description: The transaction hash
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "404":
          description: Transaction not found
  /transaction:
    post:
      summary: Submit a signed transaction
      operationId: submitTransaction
      requestBody:
        description: The transaction payload in hex.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Receipt"
        "500":
          description: Runtime failure
  /manifest:
    post:
      summary: Sign a manifest using the shared key pair.
      operationId: signManifest
      requestBody:
        description: The manifest content.
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "500":
          description: Runtime failure
components:
  schemas:
    AnyValue: {}
    Transaction:
      type: object
      properties:
        hash:
          type: string
        manifest:
          type: string
        nonce:
          type: integer
        signatures:
          type: array
          items:
            type: object
            properties:
              publicKey:
                type: string
              signature:
                type: string
      required:
        - hash
        - manifest
        - nonce
        - signatures
    Receipt:
      type: object
      properties:
        status:
          type: string
        outputs:
          type: array
          items:
            $ref: "#/components/schemas/AnyValue"
        logs:
          type: array
          items:
            type: string
        newEntities:
          type: object
          properties:
            packages:
              type: array
              items:
                type: string
            components:
              type: array
              items:
                type: string
            resources:
              type: array
              items:
                type: string
          required:
            - packages
            - components
            - resources
      required:
        - status
        - outputs
        - logs
        - newEntities
    Component:
      type: object
      properties:
        blueprint:
          type: object
          properties:
            packageAddress:
              type: string
            blueprintName:
              type: string
          required:
            - packageAddress
            - blueprintName
        authorization:
          $ref: "#/components/schemas/AnyValue"
        state:
          $ref: "#/components/schemas/AnyValue"
        ownedResources:
          type: array
          items:
            type: object
            properties:
              amount:
                type: string
              resourceAddress:
                type: string
              name:
                type: string
              symbol:
                type: string
            required:
              - amount
              - resourceAddress
              - name
              - symbol
    Resource:
      type: object
      properties:
        resourceType:
          type: string
        divisibility:
          type: integer
        metadata:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: string
        totalSupply:
          type: string
      required:
        - resourceType
        - divisibility
        - metadata
        - totalSupply
